PackageIdentifier: Cloudflare.Warp
PackageVersion: 2024.3.409.0
InstallerLocale: en-US
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Custom: /NORESTART
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.EdgeWebView2Runtime
      MinimumVersion: 91.0.864.53
ProductCode: "{09A93196-13D8-4CCF-ADE3-CF88E9174F90}"
Installers:
  - Architecture: x64
    InstallerUrl: https://1111-releases.cloudflareclient.com/windows/Cloudflare_WARP_Release-x64.msi
    InstallerSha256: A49B10DB59C8FC48723EC1BA98C23AE06552D39ACE6ABC42839846C7A77D19AE
ManifestType: installer
ManifestVersion: 1.5.0
